pipeline {
    agent any
    
    tools {
        // Define the Maven installation
        maven 'Maven 3.8.8'
    }
    
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh 'echo "running delivery and updating file permission"'
                sh 'chmod +x ./jenkins/scripts/deliver.sh'
                sh 'echo "permission assigned"'
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Deliver') {
            steps {
                echo '------------------BUILD COMPLETED----------------';
            }
        }
    }
}
